[package]
name = "oelf"
version = "0.0.4"
edition = "2021"

[lib]
name = "oelf"
crate-type = ["cdylib"]

[dependencies]
goblin = "0.7.1"
pyo3 = { version = "0.20.0", features = ["extension-module"] }
